### ISSUE TITLE
Question: timers and access to shared variable - lock needed?

### ISSUE THREAD

**Issue by hbeni** [bkacjios/lua-mumble#22]
Hi, I have a question regarding threads safety in lua-mumble timers.

:question: What happens, if at the same time the hook adds/reads data, and the timer `nil`s that table?
Will this work (because the reference to the table inside the timer is still valid), or do I need some sort of locking (if so, what exactly?)

Given I have a complex `sharedTable` table:
```lua
sharedTable = {
  1 = {
    name:"somename",
    lastUpdate:12345
  },
  2 = {...},
  ...
}
```

In the hook `OnPluginData` I add and manipulate entries to that table.

I want to regularly clean out entries not updated for a prolonged time and maintain the `lastUpdate` timestamp for that.
I also have a `mumble.timer` iterating over that table each 60 seconds. It will set stale entries to `sharedTable[userID] = nil` so they are deleted from the table.

**Comment by bkacjios** [comment]
Should be fine. The mumble.loop function creates an event loop where all hooks and io events, including timers, are handled. This event loop will be the same thread that Lua is running on. This event loop is all handled by [libev](https://github.com/enki/libev). The internal audio processing is using the same stuff that a mumble.timer uses.

Hooks can't happen at the same time as a timer since they are all being processed on the same event loop.

**Comment by hbeni** [comment]
Good to know, thank you!

So also timers cant collide?

Maybe, just as an idea, it would be good to add a sentence to the readme.

**Comment by bkacjios** [comment]
Yeah. Multiple timers can't collide either. It's all done on the same thread.

**Comment by hbeni** [comment]
Great!

and what happens, when the execution time of the timers exceed the time available before the next slot starts? Are they just skipped?

And additionally; what happens when hooks are called in the situation?

(In know this is a completely overload scenario and probably a design error of the bot in question for the most cases.
However, my bot keeps track of users in the channel and maintains a table for that, and iterating that table costs time and thus a linear thread behaviour puts a natural limit to the users supported by the bot)

**Comment by bkacjios** [comment]
I'm not quite sure I understand what you're asking. Are you saying your callback in your timer locks up the tread for a significant amount of time?

**Comment by hbeni** [comment]
It is a somewhat hypothetical question and I have no real cause for that.
I‘m just curious what to expect under heavy load situations.

**Comment by bkacjios** [comment]
Best I can guess, is that if your timer callback function is suddenly blocking the thread for a long period of time, it's going to stop pretty much everything. Audio output will halt, and hooks will be held until the callback function finishes. When it does finish, any events that were waiting will be called immediately afterwards.

You can read up on [libev's timers](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#code_ev_timer_code_relative_and_opti) since it will probably explain it better than I can. But from what I know, if the timer is repeating and the callback takes longer than the repeat delay, it's not going to retroactively call it multiple times because it missed the mark. Like say you have a repeating timer on a 0.5 second delay and your callback takes 2 seconds, it's just going to keep repeating as fast as it can while being limited to the time it takes.

If you take that same 0.5 second repeating timer but it takes 0.2 seconds to run the callback, it's going to start executing again in 0.3 seconds to make up for the lack of time. It will adjust itself to stay as close as possible to that 0.5 second delay.

**Comment by hbeni** [comment]
Thanks for clarifying!
