### ISSUE TITLE
Segmentation Fault in the resampler

### ISSUE THREAD

**Issue by duarm** [bkacjios/lua-mumble#25]
found a bug with what appears to be the resampler

Playing an ogg with the default sample rate of 48000 works, but trying to play an ogg with a different sample rate (e.g. 44100) gives me a segmentation fault somewhere around here https://github.com/bkacjios/lua-mumble/blob/cbc587557c43d3303fa165e272c44eeaf0685272/mumble/audio.c#L246

I'll make a coredump when I'm able.

**Comment by bkacjios** [comment]
Did you ever figure this out? I implemented a new resampler that uses linear interpolation in the async-connect branch, along with some other big changes.

**Comment by duarm** [comment]
running latest master 619d5f4, built with `make debug` lua 5.1.5-12, arch linux
```
        Signal: 11 (SEGV)
     Timestamp: Fri 2024-12-20 00:43:56 -03 (12s ago)
  Command Line: /bin/lua5.1 ./main.lua
    Executable: /usr/bin/lua5.1
...
       Message: Process 1485573 (main.lua) of user 1000 dumped core.
                
                Stack trace of thread 1485573:
                #0  0x0000750ee11ae21e luaL_traceback (libluajit-5.1.so.2 + 0x1821e)
                #1  0x0000750ee132742c mumble_traceback (mumble.so + 0x2442c)
                #2  0x00006347eb3f2ced n/a (n/a + 0x0)
                #3  0x00006347eb3f15dd n/a (n/a + 0x0)
                #4  0x00006347eb3f18e7 n/a (n/a + 0x0)
                #5  0x00006347eb3ef466 n/a (n/a + 0x0)
                #6  0x00006347eb3f2de7 n/a (n/a + 0x0)
                #7  0x00006347eb3fc769 n/a (n/a + 0x0)
                #8  0x00006347eb3f160d n/a (n/a + 0x0)
                #9  0x00006347eb3eda02 n/a (n/a + 0x0)
                #10 0x00006347eb3ee709 n/a (n/a + 0x0)
                #11 0x00006347eb3ee84f n/a (n/a + 0x0)
                #12 0x0000750ee1327635 mumble_hook_call_ret (mumble.so + 0x24635)
                #13 0x0000750ee1327467 mumble_hook_call (mumble.so + 0x24467)
                #14 0x0000750ee132e28a packet_text_message (mumble.so + 0x2b28a)
                #15 0x0000750ee132529d socket_read_event_tcp (mumble.so + 0x2229d)
                #16 0x0000750ee0c5d13b ev_invoke_pending (libev.so.4 + 0x513b)
                #17 0x0000750ee0c60d22 ev_run (libev.so.4 + 0x8d22)
                #18 0x0000750ee1326e1c mumble_loop (mumble.so + 0x23e1c)
                #19 0x00006347eb3f2ced n/a (n/a + 0x0)
                #20 0x00006347eb3fc769 n/a (n/a + 0x0)
                #21 0x00006347eb3f160d n/a (n/a + 0x0)
                #22 0x00006347eb3eda02 n/a (n/a + 0x0)
                #23 0x00006347eb3ee709 n/a (n/a + 0x0)
                #24 0x00006347eb3ee84f n/a (n/a + 0x0)
                #25 0x00006347eb3f371c n/a (n/a + 0x0)
                #26 0x00006347eb3f92fc n/a (n/a + 0x0)
                #27 0x00006347eb3f2ced n/a (n/a + 0x0)
                #28 0x00006347eb3f15dd n/a (n/a + 0x0)
                #29 0x00006347eb3eda02 n/a (n/a + 0x0)
                #30 0x00006347eb3ee709 n/a (n/a + 0x0)
                #31 0x00006347eb3ee8ee n/a (n/a + 0x0)
                #32 0x00006347eb3ea0d2 n/a (n/a + 0x0)
                #33 0x0000750ee13f3e08 n/a (libc.so.6 + 0x25e08)
                #34 0x0000750ee13f3ecc __libc_start_main (libc.so.6 + 0x25ecc)
                #35 0x00006347eb3ea1a5 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
~
~
```

bot code is a simple hook.lua example with a client:play

```lua
client:hook("OnMessage", function(client, event)
	client:play("/home/me/music/persona_4/Arena_Ultimax_Opening.ogg", 1, 0.5)
end)
```
I'll try to debug it further with asan instead of printf when I get some time

**Comment by bkacjios** [comment]
So.. it looks like its crashing in the error handler. It's erroring because client:play no longer exists. I made it client:openOgg instead which returns an audiostream object that you can then call play on. I'd go through the readme to see a lot of the API changes I made.

It looks like its crashing on luaL_traceback, which is used to get the error message.. You're using luajit by the looks of it, so that function should be linked from libluajit. You may want to do a clean build, since it looks like something went wrong there.

Also, if you made a debug build, if you run it using gdb and get it to crash, you can get a much more detailed crash log.

`gdb --args luajit ./yourscript.lua`

When it crashes, you can use the command `bt` to get a backtrace with files and lines.

**Comment by bkacjios** [comment]
So I figured out the issue you were having. You compiled the module for luajit, but you're using Lua5.1's executable to run. This will cause a crash, since in Lua5.1 `luaL_traceback` doesn't exist. If you compile lua-mumble for 5.1, it will create its own implementation and not crash. Either use the luajit executable or compile the module for lua5.1.

**Comment by duarm** [comment]
The error was happening even before the API changes, but I guess the problem might've been the lua version, as I'm indeed using puc lua 5.1 to run, and compiling with luajit (the default), I'll try to reproduce again. Thank you very much for the help

**Comment by duarm** [comment]
Tried a 44100 bitrate and it works, it was probably due to the luajit problem

**Comment by bkacjios** [comment]
Gotcha. Glad you got it figured out!
